### ISSUE TITLE
Invalid number of arguments provided to `main.jl`

### ISSUE THREAD

**Issue by HTofi** [mason-org/julia-lsp#10]
Hello,

My Julia LSP stopped working after updating the extension today. It seems this is caused by a recent [commit](https://github.com/julia-vscode/julia-vscode/commit/4a80d48da78995c570aca6d996aa6664877a37d6) to julia-vscode which added two additional arguments to `main.jl`, meanwhile the bash [wrapper](https://github.com/mason-org/julia-lsp/blob/main/bin/julia-lsp) still provides 8 arguments only.

**Comment by williamboman** [comment]
Should be fixed in #9.
