### ISSUE TITLE
Extend repo to use julia formatter

### ISSUE THREAD

**Issue by gnuille** [mason-org/julia-lsp#2]
Hi! I'm not sure if this is the proper way to approach.
I was adding to `mason-registry` the Julia Formatter (https://github.com/domluna/JuliaFormatter.jl)

While doing so I was getting inspired by `julia-lsp` package and I ended up here. Should we use this repo or create another for running the formatter as a binary standalone or should I approach this in another way?

Thanks :)

**Comment by williamboman** [comment]
Hello! I assume they don't provide their own executable? Is their recommendation really to run the formatter interactively via the Julia console? I'm not sure I want to introduce custom interfaces that doesn't align with upstream practices. This wrapper only really exists as a means to make the Julia language server available via mason (the other option would've been to drop support for it).

**Comment by mehalter** [comment]
@gnuille the `julia-lsp` package uses `julia-vscode` and `julia-vscode` (since v1.5) uses JuliaFormatter.jl for the formatting support that is built into the language server protocol.

**Comment by lassepe** [comment]
I think this issue can be closed. There is nothing to do here; it works out of the box.
