### ISSUE TITLE
Consider disabling symbolserver downloads

### ISSUE THREAD

**Issue by dermesser** [mason-org/julia-lsp#3]
Thank you for this extension - I'm using it almost daily. However,  LanguageServer appears to try downloading symbol caches for Julia packages, which fails for unknown reasons (and has failed always as far back as I can remember).

* https://discourse.julialang.org/t/failure-to-retrieve-cache-files-with-language-server/72489
* https://github.com/julia-vscode/julia-vscode/issues/2880
* and some other reports.

May I suggest disabling by default, or documenting the "download" option in the startup script (https://github.com/mason-org/julia-lsp/blob/main/bin/julia-lsp#L29) to avoid triggering downloads? Then the languageserver indexes packages locally, which is much faster than attempting and failing to download dozens or even more packages.

**Comment by williamboman** [comment]
Added in #4 with convenience settings in mason-lspconfig here: https://github.com/williamboman/mason-lspconfig.nvim/pull/217.

See https://github.com/williamboman/mason-lspconfig.nvim/blob/main/lua/mason-lspconfig/server_configurations/julials/README.md#configuring-symbol-cache
